### ISSUE TITLE
[CV] Прогресс

### ISSUE THREAD

**Issue by schrodinger-cat** [alinasalnikova/path-of-the-Padawan#1]
```css
.s-progress{
    width: 180px;
    height: 4px;
}
```

1. Не стоит называть класс аббревиатурой, хотя бы потому что через пару дней ты голову сломаешь думая над её расшифровкой. В данном случае я бы назвал просто `sketch`
2. Тебе не кажется что задавать высоту в каждом подобном классов избыточно? Подумай как это можно сделать в одном месте и не дублировать себя
3. Используй проценты для ширины. По логике макета – это резюме в котором прогресс оценивает на сколько хорошо ты знаешь ту или иную технологию.  Эту метрику, как по мне, удобнее выражать в процентах. (ты же не скажешь что владеешь скетчем на 180 пикселей?  😁)

В остальном, это верное решение.

**Comment by alinasalnikova** [comment]
@schrodinger-cat 
1. поменяла классы индикаторов с аббревиатуры на полное название, потому что в div уже ранее прописала progress
2. перенесла высоту из каждого класса в класс .progress
3. поменяла единицы на % и добавила для класса .list отступ справа, потому что без этого индикаторы тянутся до конца класса .container
